### ISSUE TITLE
ring-daemon not compiling

### ISSUE THREAD

**Issue by fcolecumberri** [stefan-langenmaier/ring-overlay#61] opened 2019-06-28 22:38 UTC
jamiaccount.cpp:3628:13: error: ‘registeredName_’ was not declared in this scope
     if (not registeredName_.empty())
             ^~~~~~~~~~~~~~~
jamiaccount.cpp:3628:13: note: suggested alternative: ‘register_t’
     if (not registeredName_.empty())
             ^~~~~~~~~~~~~~~
             register_t
make[4]: *** [Makefile:589: libringacc_la-jamiaccount.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/var/tmp/portage/net-voip/ring-daemon-20190608.1/work/ring-project/daemon/src/jamidht'
make[3]: *** [Makefile:632: all-recursive] Error 1
make[3]: Leaving directory '/var/tmp/portage/net-voip/ring-daemon-20190608.1/work/ring-project/daemon/src/jamidht'
make[2]: *** [Makefile:1035: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-voip/ring-daemon-20190608.1/work/ring-project/daemon/src'
make[1]: *** [Makefile:540: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/net-voip/ring-daemon-20190608.1/work/ring-project/daemon'
make: *** [Makefile:471: all] Error 2

[build.log](https://github.com/stefan-langenmaier/ring-overlay/files/3341073/build.log)

**Comment by stefan-langenmaier** [comment] 2019-07-03 20:36
Hi @fcolecumberri ,

thanks for your detailed bug report. Unfortunately I was not able to reproduce the issue. Could you also send the output of `emerge --info`?

Did it work in earlier version of the ebuild? Btw, I have bumped the ebuild to a newer version.

**Comment by fcolecumberri** [comment] 2019-07-06 20:17
here it is

[ring-daemon.txt](https://github.com/stefan-langenmaier/ring-overlay/files/3364988/ring-daemon.txt)

**Comment by stefan-langenmaier** [comment] 2019-07-07 21:13
I'm using gcc-8.3 for the compilation. I'm not sure if it is related but maybe you can switch to it and try again.

**Comment by fcolecumberri** [comment] 2019-07-08 19:12
ok, changed gcc with eselect to x86_64-pc-linux-gnu-8.3.0 and same result

**Comment by stefan-langenmaier** [comment] 2020-04-14 17:53
I'm closing this as there are newer versions available. Let me know if there is still a problem with the latest version.

**Closed by stefan-langenmaier** 2020-04-14 17:53 UTC
